language: cpp
compiler: gcc
env: 
  matrix: 
    allow_failures: 
      os: linux
before_install:
  # g++4.8.1
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi

  - sudo apt-get update -qq
  

install:
  # g++4.8.1
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi

  - BASHRC=/home/travis/build/.bashrc
  - sudo apt-get install libboost-dev
  - sudo apt-get install libnuma-dbg
  - sudo apt-get install libnuma-dev
  - sudo apt-get install libnuma1
  - sudo apt-get install numactl
  - pwd
  - cd ./thirdparty/libxs-1.2.0
  - pwd
  - ls -la
  - chmod 777 configure
  - chmod 777 version.sh
  - ./configure
  - sudo make check -j4
  - sudo make install && sudo ldconfig
  - cd ../Theron-5.01.01
  - export THERON_HOME=/home/travis/build/Jackson1992/test_parser/thirdparty/Theron-5.01.01>>${BASHRC}
  - source ${BASHRC}
  - echo ${THERON_HOME}
  - ls -l /usr/lib/debug/usr/lib/
  - sudo find / -name xs_d
  - make -j4 xs=on mode=debug



script:
 - $CXX --version
 - cat ~/.bashrc
 - cd ..
 - ls -la
