language: cpp
compiler: gcc 4.8
script:
 - ./build.sh init
 - ./configure --prefix=/home/travis/build/Jackson1992/test_parser/install 
 - sudo make 
 - sudo make install
 - ls
 - cd ./test && ls
 - cd  ./main && ls
 - ./parser_test
