language: cpp
compiler: gcc
script:
 - sudo apt-get update
 - sudo apt-cache search libxs-dev
 - find . -name "libxs"
 - ./build.sh init
 - pwd
 - ./configure --prefix=/home/travis/build/Jackson1992/test_parser/install 
 - sudo make 
 - sudo make install
