language: cpp
compiler: gcc
script:
 - cd /usr/bin
 - ls
 - ./build.sh init
 - pwd
 - ./configure --prefix=/home/travis/build/Jackson1992/test_parser/install 
 - sudo make 
 - sudo make install
