language: cpp
compiler: gcc
before_install:
  # g++4.8.1
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi

  - sudo apt-get update -qq

install:
  # g++4.8.1
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi

  - sudo apt-get install libboost-dev
  - sudo apt-get install libnuma-dbg
  - sudo apt-get install libnuma-dev
  - sudo apt-get install libnuma1
  - sudo apt-get install numactl
  - pwd
  - cd ./thirdparty/libxs-1.2.0
  - pwd
  - ls -la
  - chmod 777 configure
  - chmod 777 version.sh
  - ./configure
  - sudo make check -j4
  - sudo make install && sudo ldconfig


script:
 - $CXX --version
 - cat ~/.bashrc
 - cd ..
 - ls -la
